stages:
  - package_binary_main
  - package_binary_preview
  - build_image_main
  - build_image_preview

# request，limit表示允许使用的最大资源
# CPU单位是m, 对应1/1000core. 比如100m表示0.1core；Memory单位是Mi或Gi, 对应MB/GB. 比如100Mi表示100MB
variables:
  KUBERNETES_CPU_REQUEST: 4000m
  KUBERNETES_CPU_LIMIT: 8000m
  KUBERNETES_MEMORY_REQUEST: 4Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi

# 测试
package_binary_main:
  stage: package_binary_main
  script:
    - mkdir output
    - cp -r `ls |grep -v output|xargs` ./output
  artifacts:
    paths:
      - output/
  only:
    refs:
      - main

# 线上
package_binary_preview:
  stage: package_binary_preview
  script:
    - mkdir output
    - cp -r `ls |grep -v output|xargs` ./output
  artifacts:
    paths:
      - output/
  only:
    refs:
      - preview

build_image_main:
  stage: build_image_main
  image:
    name: micr.cloud.mioffice.cn/containercloud/kaniko-executor-xiaomi:release
    entrypoint: [ "" ]
  script:
    - export APP_IMAGE=$REPO_SERVER/$REPO_NAMESPACE/mify-agent:main-$CI_COMMIT_SHORT_SHA
    - echo "{\"auths\":{\"$REPO_SERVER\":{\"username\":\"$REPO_USER\",\"password\":\"$REPO_PASS\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $APP_IMAGE --validate-image
  only:
    refs:
      - main
  tags:
    - special-shared


build_image_preview:
  stage: build_image_preview
  image:
    name: micr.cloud.mioffice.cn/containercloud/kaniko-executor-xiaomi:release
    entrypoint: [ "" ]
  script:
    - export APP_IMAGE=$REPO_SERVER/$REPO_NAMESPACE/mify-agent:preview-$CI_COMMIT_SHORT_SHA
    - echo "{\"auths\":{\"$REPO_SERVER\":{\"username\":\"$REPO_USER\",\"password\":\"$REPO_PASS\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $APP_IMAGE --validate-image
  only:
    refs:
      - preview
  tags:
    - special-shared
