version: '3'

services:
  mi-app:
    build: 
      context: .
      args:
        BUILD_DATE: "${BUILD_DATE:-20250327}"
    image: mi-app:v${BUILD_DATE:-20250327}
    container_name: mi-app
    ports:
      - "9051:80"
    restart: unless-stopped
